### ISSUE TITLE
Schematic Design

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#2]
Karamjot - What issues did you face when working with EasyEDA?

**Comment by karamjotkaur** [comment]
EasyEDA is a simple software that is used to design schematic capture. It is easy to select components just by one click once you practiced the software. I faced some issues in the first couple of tries, and the following are the issues that I faced during the process of schematic design:
1.  Initially, when I started searching the components, the software was slow, and it was taking multiple search attempts to find a component. E.g., I tried to find BeagleBone Black and typed the name in the library's search bar. But the required component was not shown in the first attempt. I had to search repeatedly, and I went through all the options such as symbols, spice symbols, footprints, etc. to find it.
2.  Moreover, components' footprints are missing, and I couldn't find a way to design them. As we need footprints for PCB design, I could not convert my schematic capture into PCB design.
3.  In addition to this, sometimes I faced problems while wiring like the wire was not connecting properly to the main MCU that is BeagleBone Black. When I start and end the wire's at both ends, a dot confirms that the connection has been made. But when I was making the connection, the dot was missing at the connection of MCU. To solve this problem, I had remove and select components on the sheet over and over again.
4.   Furthermore, in the beginning, I faced problems in placing components in the workspace sheet as I did not know about the Esc key to cancel the current drawing. At that point, the component was placed multiple times, and wires were creating a mess. Once I learned about this shortcut, everything was smooth. 
5.   Lastly, easyEDA does not have any 3D components for schematic design. There is no option of adding any animation to the design, and there are only 2D design options for schematic captures.
